#!/bin/ksh -l
#dis
#dis    Open Source License/Disclaimer, Forecast Systems Laboratory
#dis    NOAA/OAR/FSL, 325 Broadway Boulder, CO 80305
#dis
#dis    This software is distributed under the Open Source Definition,
#dis    which may be found at http://www.opensource.org/osd.html.
#dis
#dis    In particular, redistribution and use in source and binary forms,
#dis    with or without modification, are permitted provided that the
#dis    following conditions are met:
#dis
#dis    - Redistributions of source code must retain this notice, this
#dis    list of conditions and the following disclaimer.
#dis
#dis    - Redistributions in binary form must provide access to this
#dis    notice, this list of conditions and the following disclaimer, and
#dis    the underlying source code.
#dis
#dis    - All modifications to this software must be clearly documented,
#dis    and are solely the responsibility of the agent making the
#dis    modifications.
#dis
#dis    - If significant modifications or enhancements are made to this
#dis    software, the FSL Software Policy Manager
#dis    (softwaremgr@fsl.noaa.gov) should be notified.
#dis
#dis    THIS SOFTWARE AND ITS DOCUMENTATION ARE IN THE PUBLIC DOMAIN
#dis    AND ARE FURNISHED "AS IS."  THE AUTHORS, THE UNITED STATES
#dis    GOVERNMENT, ITS INSTRUMENTALITIES, OFFICERS, EMPLOYEES, AND
#dis    AGENTS MAKE NO WARRANTY, EXPRESS OR IMPLIED, AS TO THE USEFULNESS
#dis    OF THE SOFTWARE AND DOCUMENTATION FOR ANY PURPOSE.  THEY ASSUME
#dis    NO RESPONSIBILITY (1) FOR THE USE OF THE SOFTWARE AND
#dis    DOCUMENTATION; OR (2) TO PROVIDE TECHNICAL SUPPORT TO USERS.
#dis
#dis

##########################################################################
#
#Script Name: batchTemplate-ncl
# 
#     Author: Christopher Harrop
#             Forecast Systems Laboratory
#             325 Broadway R/FST
#             Boulder, CO. 80305
#
#   Released: 10/30/2003
#    Version: 1.0
#    Changes: None
#
# Purpose: This script generates NCL graphics from wrf output.  
#
#               EXE_ROOT = The full path of the ncl executables
#          MOAD_DATAROOT = Top level directory of wrf output and
#                          configuration data.
#             START_TIME = The cycle time to use for the initial time. 
#                          If not set, the system clock is used.
#              FCST_TIME = The two-digit forecast that is to be ncled
# 
# A short and simple "control" script could be written to call this script
# or to submit this  script to a batch queueing  system.  Such a "control" 
# script  could  also  be  used to  set the above environment variables as 
# appropriate  for  a  particular experiment.  Batch  queueing options can
# be  specified on the command  line or  as directives at  the top of this
# script.  A set of default batch queueing directives is provided.
#
##########################################################################

CONTEXT="batchTemplate-ncl"

## load modules
module load intel
module load ncl/6.5.0

CONVERT=`which convert`
MONTAGE=`which montage`
echo "CONVERT: $CONVERT"
echo "MONTAGE: $MONTAGE"

NCL=`which ncl`
CTRANS=`which ctrans`
echo "NCL: $NCL"
echo "CTRANS: $CTRANS"

#.  ${SCRIPTS}/chem_functions.ksh
#chem_on && CHEMFLAG="true" || CHEMFLAG="false"
CHEMFLAG="false"
chem_opt_value=0
echo "chem_opt_value: $chem_opt_value"
echo "************** in ncl MODL: $MODL"


# Make sure we are using GMT time zone for time computations
export TZ="GMT"

# Execute module command to use newest version of NCL
# module switch ncarg ncl
# UDUNITS=`which udunits`
# export UDUNITS2_XML_PATH=${NCARG_ROOT}/lib/ncarg/udunits/udunits2.xml

echo "NCARG_ROOT: $NCARG_ROOT"

# Set up paths to shell commands
LS=/bin/ls
LN=/bin/ln
RM=/bin/rm
MKDIR="/bin/mkdir -m 775"
CP=/bin/cp
MV=/bin/mv
ECHO=/bin/echo
CAT=/bin/cat
GREP=/bin/grep
CUT=/bin/cut
AWK="/bin/gawk --posix"
SED=/bin/sed
DATE=/bin/date
BC=/usr/bin/bc

PS2PDF=/usr/bin/ps2pdf
PATH=${NCARG_ROOT}/bin:${PATH}

# Set ISDIR
ISDIR="NAT"

# Location of NCL graphics scripts
NCL_ROOT=${FV3GFS_HOME}/FV3GFSwfm/ncl/fimall

typeset -Z3 FCST_TIME FCST_TIME_BACK6 FCST_TIME_BACK12 FCST_TIME_BACK24 FCST_TIME_AHEAD12 FCST_TIME_AHEAD24

# Generate the ATCFNAME for this member
ATCFNAME=`echo ${ATCFNAME} | sed "s/NN/${MEMBER_ID}/"`

FCST_TIME=${T}
FCST_TIME_BACK6=-999
FCST_TIME_BACK12=-999
FCST_TIME_BACK24=-999
if (( ${FCST_TIME} >= 6 )); then
  FCST_TIME_BACK6=$(($FCST_TIME - 6))
fi
if (( ${FCST_TIME} >= 12 )); then
  FCST_TIME_BACK12=$(($FCST_TIME - 12))
fi
if (( ${FCST_TIME} >= 24 )); then
  FCST_TIME_BACK24=$(($FCST_TIME - 24))
fi

# Print run parameters
${ECHO}
${ECHO} "batchTemplate-ncl started at `${DATE}`"
${ECHO}
${ECHO} "    FV3GFS_RUN=${FV3GFS_RUN}"
${ECHO} "      yyyymmdd=${yyyymmdd}"
${ECHO} "             H=${H}"
${ECHO} "     yyjjjhhmm=${yyjjjhhmm}"
${ECHO} "             T=${T}"
${ECHO} "     FCST_TIME=${FCST_TIME}"
${ECHO} "   FCST_LENGTH=${FCST_LENGTH}"
${ECHO} "         ISDIR=${ISDIR}"
${ECHO} "         CDUMP=${CDUMP}"
${ECHO} "     GRID_NAME=${GRID_NAME}"
${ECHO} "          MODL=${MODL}"
${ECHO}

# Link to input files
if (( ${GRID_NAME} == "fim" )); then
  g2_file=${CDUMP}.t${H}z.pgrb2.${RES}.f${T}    ## gfs.t00z.pgrb2.0p50.f###
  g1_file=${CDUMP}.t${H}z.pgrbh${FCST_TIME}     ## gfs.t00z.pgrbh[#]##
  ${LN} -fs ${FV3GFS_RUN}/${g2_file} ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME}.g2 
fi

# Set up the work directory and cd into it
workdir=${FV3GFS_RUN}/ncl/${GRID_NAME}/${ISDIR}_${FCST_TIME}
${ECHO} " JKH:  workdir= $workdir"
${RM} -rf ${workdir}
${MKDIR} -p ${workdir}
cd ${workdir}

# Link to input files
${LN} -s ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME}.g2 fv3.grb
${ECHO} "fv3.grb" > arw_file.txt
if (( ${GRID_NAME} == "fim" )); then
  ${LN} -s ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME} fv3.grb1
  ${ECHO} "fv3.grb1" > arw_file_grib1.txt
else
  ${LN} -s ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME}.weasd fv3.grb1
  ${ECHO} "fv3.grb1" > arw_file_grib1.txt
fi
if (( ${FCST_TIME} >= 6 )); then
  ${LN} -s ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME_BACK6}.g2 back6file.grb
  ${ECHO} "back6file.grb" > back6_file.txt
fi
if (( ${FCST_TIME} >= 12 )); then
  ${LN} -s ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME_BACK12}.g2 back12file.grb
  ${ECHO} "back12file.grb" > back12_file.txt
  ls -al back12file.grb
fi
if (( ${FCST_TIME} >= 24 )); then
  ${LN} -s ${FV3GFS_RUN}/post/${GRID_NAME}/${yyjjjhhmm}0${FCST_TIME_BACK24}.g2 back24file.grb
  ${ECHO} "back24file.grb" > back24_file.txt
fi

yyyymmddhh_BACK12=$( date +"%Y%m%d %H" -d "${datestr} 12 hours ago" )
yyyymmddhh_BACK24=$( date +"%Y%m%d %H" -d "${datestr} 24 hours ago" )
yyjjjhhmm_BACK12=$( date +"%y%j%H%M" -d "${yyyymmddhh_BACK12}" )
yyjjjhhmm_BACK24=$( date +"%y%j%H%M" -d "${yyyymmddhh_BACK24}" )
yyyymmddhh_BACK12=$( date +"%Y%m%d%H" -d "${yyyymmddhh_BACK12}" )
yyyymmddhh_BACK24=$( date +"%Y%m%d%H" -d "${yyyymmddhh_BACK24}" )
back12ymd=`echo $yyyymmddhh_BACK12 | cut -c1-8`
back12hr=`echo $yyyymmddhh_BACK12 | cut -c9-10`
back24ymd=`echo $yyyymmddhh_BACK24 | cut -c1-8`
back24hr=`echo $yyyymmddhh_BACK24 | cut -c9-10`
BACK12dir=gfs.${back12ymd}/${back12hr}
BACK24dir=gfs.${back24ymd}/${back24hr}

# To be valid at the same time, FCST_TIME_AHEAD12 matches with yyyymmddhh_BACK12,
# and FCST_TIME_AHEAD24 matches with yyyymmddhh_BACK24

FCST_TIME_AHEAD12=99
FCST_TIME_AHEAD24=99
FCST_LENGTH_BACK12=$(($FCST_LENGTH - 12))
if (( ${FCST_TIME} < ${FCST_LENGTH_BACK12} )); then
  FCST_TIME_AHEAD12=$(($FCST_TIME + 12))
  FCST_TIME_AHEAD24=$(($FCST_TIME + 24))
else
  if (( ${FCST_TIME} == ${FCST_LENGTH_BACK12} )); then
    FCST_TIME_AHEAD12=$(($FCST_TIME + 12))
  fi
fi


${LN} -s ${FV3GFS_RUN}/${BACK12dir}/post/${GRID_NAME}/${yyjjjhhmm_BACK12}0${FCST_TIME_AHEAD12}.g2 back1run.grb
${LN} -s ${FV3GFS_RUN}/${BACK24dir}/post/${GRID_NAME}/${yyjjjhhmm_BACK24}0${FCST_TIME_AHEAD24}.g2 back2run.grb
${ECHO} "back1run.grb" > back1_run.txt
${ECHO} "back2run.grb" > back2_run.txt




# Setup domain file
${ECHO} ${GRID_NAME} > domain.txt

# Link to tracker file
#if [ -s ${FV3GFS_RUN}/${yyyymmdd}${hh}/posttracker_${MEMBER_ID}/168/track.${yyyymmddhhmm}.${ATCFNAME} ]; then
#  ${CAT} ${FV3GFS_RUN}/${yyyymmdd}${hh}/posttracker_${MEMBER_ID}/168/track.${yyyymmddhhmm}.${ATCFNAME} | ${SED} 's/\*\*\*/  0/' > ./track.${yyyymmddhhmm}
#  ${ECHO} ./track.${yyyymmddhhmm} > track_file.txt
#fi

modelFound=0

if [ "${ISDIR}" == "NAT" ]; then

  if [[ "$MODL" = *ccpp* || "$MODL" = *FV3* ]]; then

    modelFound=1
    echo "This is FIM-8, FIM-9, FIMX, FIMY, FIMZ, FIMALT, FIM7ALT, FIMXALT FV3GFS"

    set -A ncgms  sfc_temp    \
                  850_wind    \
                  250_wind    \
                  25_wind     \
                  20_wind     \
                  10_wind     \
                  5_wind      \
                  850_wmag    \
                  250_wmag    \
                  25_wmag     \
                  20_wmag     \
                  10_wmag     \
                  5_wmag      \
                  sfc_pwtr    \
                  sfc_cwat    \
                  sfc_mslp    \
                  10_temp     \
                  500_temp    \
                  700_temp    \
                  850_temp    \
                  925_temp    \
                  500_hgt     \
                  ua_rh       \
                  850_rh      \
                  500_vort    \
                  700_vvel    \
                  sfc_shtfl   \
                  sfc_lhtfl   \
                  sfc_dswrf   \
                  sfc_dlwrf   \
                  sfc_uswrf   \
                  sfc_ulwrf   \
                  nta_ulwrf   \
                  2m_temp     \
                  2ds_temp    \
                  2m_dewp     \
                  10m_wind    \
                  80m_wind    \
                  sfc_totp    \
                  12h_totp    \
                  24h_totp    \
                  sfc_acp     \
                  esbl_hvyacp \
                  sfc_acpcp   \
                  sfc_weasd   \
                  sfc_acsnw   \
                  sfc_totsn   \
                  12h_totsn   \
                  24h_totsn   \
                  ua_ceil     \
                  ua_ctop     \
                  sfc_rhpw    \
                  sfc_fd      \
                  sfc_bc      \
                  sfc_oc      \
                  sfc_sulf    \
                  sfc_seasalt \
                  sfc_PM10    \
                  sfc_PM25    \
                  col_fd      \
                  col_bc      \
                  col_oc      \
                  col_sulf    \
                  col_seasalt \
                  col_PM10    \
                  col_PM25    \
                  col_tozne   \
                  sfc_aodfd   \
                  sfc_aodbc   \
                  sfc_aodoc   \
                  sfc_aodsulf \
                  sfc_aodseasalt \
                  sfc_aodtot  \
                  sfc_aod     \
                  h50_ozone   \
                  pv2_ptemp   \
                  pv2_wind    \
                  pv2_pres

    set -A kioskncgms  10m_wind_kiosk   \
                       sfc_acp_kiosk    \
                       sfc_acsnw_kiosk

    set -A pngs sfc_temp.png    \
                850_wind.png    \
                250_wind.png    \
                25_wind.png     \
                20_wind.png     \
                10_wind.png     \
                5_wind.png      \
                850_wmag.png    \
                250_wmag.png    \
                25_wmag.png     \
                20_wmag.png     \
                10_wmag.png     \
                5_wmag.png      \
                sfc_pwtr.png    \
                sfc_cwat.png    \
                sfc_mslp.png    \
                10_temp.png     \
                500_temp.png    \
                700_temp.png    \
                850_temp.png    \
                925_temp.png    \
                500_hgt.png     \
                ua_rh.png       \
                850_rh.png      \
                500_vort.png    \
                700_vvel.png    \
                sfc_shtfl.png   \
                sfc_lhtfl.png   \
                sfc_dswrf.png   \
                sfc_dlwrf.png   \
                sfc_uswrf.png   \
                sfc_ulwrf.png   \
                nta_ulwrf.png   \
                2m_temp.png     \
                2ds_temp.png    \
                2m_dewp.png     \
                10m_wind.png    \
                80m_wind.png    \
                sfc_totp.png    \
                12h_totp.png    \
                24h_totp.png    \
                sfc_acp.png     \
                esbl_hvyacp.png \
                sfc_acpcp.png   \
                sfc_weasd.png   \
                sfc_acsnw.png   \
                sfc_totsn.png   \
                12h_totsn.png   \
                24h_totsn.png   \
                ua_ceil.png     \
                ua_ctop.png     \
                sfc_rhpw.png    \
                sfc_fd.png      \
                sfc_bc.png      \
                sfc_oc.png      \
                sfc_sulf.png    \
                sfc_seasalt.png \
                sfc_PM10.png    \
                sfc_PM25.png    \
                col_fd.png      \
                col_bc.png      \
                col_oc.png      \
                col_sulf.png    \
                col_seasalt.png \
                col_PM10.png    \
                col_PM25.png    \
                col_tozne.png   \
                sfc_aodfd.png   \
                sfc_aodbc.png   \
                sfc_aodoc.png   \
                sfc_aodsulf.png \
                sfc_aodseasalt.png \
                sfc_aodtot.png  \
                sfc_aod.png     \
                h50_ozone.png   \
                pv2_ptemp.png   \
                pv2_wind.png    \
                pv2_pres.png

    set -A pngsfim sfc_temp-0.png    \
                   sfc_temp-1.png    \
                   850_wind-0.png    \
                   850_wind-1.png    \
                   250_wind-0.png    \
                   250_wind-1.png    \
                   25_wind-0.png     \
                   25_wind-1.png     \
                   20_wind-0.png     \
                   20_wind-1.png     \
                   10_wind-0.png     \
                   10_wind-1.png     \
                   5_wind-0.png      \
                   5_wind-1.png      \
                   850_wmag-0.png    \
                   850_wmag-1.png    \
                   250_wmag-0.png    \
                   250_wmag-1.png    \
                   25_wmag-0.png     \
                   25_wmag-1.png     \
                   20_wmag-0.png     \
                   20_wmag-1.png     \
                   10_wmag-0.png     \
                   10_wmag-1.png     \
                   5_wmag-0.png      \
                   5_wmag-1.png      \
                   sfc_pwtr-0.png    \
                   sfc_pwtr-1.png    \
                   sfc_cwat-0.png    \
                   sfc_cwat-1.png    \
                   sfc_mslp-0.png    \
                   sfc_mslp-1.png    \
                   10_temp-0.png     \
                   10_temp-1.png     \
                   500_temp-0.png    \
                   500_temp-1.png    \
                   700_temp-0.png    \
                   700_temp-1.png    \
                   850_temp-0.png    \
                   850_temp-1.png    \
                   925_temp-0.png    \
                   925_temp-1.png    \
                   500_hgt-0.png     \
                   500_hgt-1.png     \
                   ua_rh-0.png       \
                   ua_rh-1.png       \
                   850_rh-0.png      \
                   850_rh-1.png      \
                   500_vort-0.png    \
                   500_vort-1.png    \
                   700_vvel-0.png    \
                   700_vvel-1.png    \
                   sfc_shtfl-0.png   \
                   sfc_shtfl-1.png   \
                   sfc_lhtfl-0.png   \
                   sfc_lhtfl-1.png   \
                   sfc_dswrf-0.png   \
                   sfc_dswrf-1.png   \
                   sfc_dlwrf-0.png   \
                   sfc_dlwrf-1.png   \
                   sfc_uswrf-0.png   \
                   sfc_uswrf-1.png   \
                   sfc_ulwrf-0.png   \
                   sfc_ulwrf-1.png   \
                   nta_ulwrf-0.png   \
                   nta_ulwrf-1.png   \
                   2m_temp-0.png     \
                   2m_temp-1.png     \
                   2ds_temp-0.png    \
                   2ds_temp-1.png    \
                   2m_dewp-0.png     \
                   2m_dewp-1.png     \
                   10m_wind-0.png    \
                   10m_wind-1.png    \
                   80m_wind-0.png    \
                   80m_wind-1.png    \
                   sfc_totp-0.png    \
                   sfc_totp-1.png    \
                   12h_totp-0.png    \
                   12h_totp-1.png    \
                   24h_totp-0.png    \
                   24h_totp-1.png    \
                   sfc_acp-0.png     \
                   sfc_acp-1.png     \
                   esbl_hvyacp-0.png \
                   esbl_hvyacp-1.png \
                   sfc_acpcp-0.png   \
                   sfc_acpcp-1.png   \
                   sfc_weasd-0.png   \
                   sfc_weasd-1.png   \
                   sfc_acsnw-0.png   \
                   sfc_acsnw-1.png   \
                   sfc_totsn-0.png   \
                   sfc_totsn-1.png   \
                   12h_totsn-0.png   \
                   12h_totsn-1.png   \
                   24h_totsn-0.png   \
                   24h_totsn-1.png   \
                   ua_ceil-0.png     \
                   ua_ceil-1.png     \
                   ua_ctop-0.png     \
                   ua_ctop-1.png     \
                   sfc_rhpw-0.png    \
                   sfc_rhpw-1.png    \
                   sfc_fd-0.png      \
                   sfc_fd-1.png      \
                   sfc_bc-0.png      \
                   sfc_bc-1.png      \
                   sfc_oc-0.png      \
                   sfc_oc-1.png      \
                   sfc_sulf-0.png    \
                   sfc_sulf-1.png    \
                   sfc_seasalt-0.png \
                   sfc_seasalt-1.png \
                   sfc_PM10-0.png    \
                   sfc_PM10-1.png    \
                   sfc_PM25-0.png    \
                   sfc_PM25-1.png    \
                   col_fd-0.png      \
                   col_fd-1.png      \
                   col_bc-0.png      \
                   col_bc-1.png      \
                   col_oc-0.png      \
                   col_oc-1.png      \
                   col_sulf-0.png    \
                   col_sulf-1.png    \
                   col_seasalt-0.png \
                   col_seasalt-1.png \
                   col_PM10-0.png    \
                   col_PM10-1.png    \
                   col_PM25-0.png    \
                   col_PM25-1.png    \
                   col_tozne-0.png   \
                   col_tozne-1.png   \
                   sfc_aodfd-0.png   \
                   sfc_aodfd-1.png   \
                   sfc_aodbc-0.png   \
                   sfc_aodbc-1.png   \
                   sfc_aodoc-0.png   \
                   sfc_aodoc-1.png   \
                   sfc_aodsulf-0.png \
                   sfc_aodsulf-1.png \
                   sfc_aodseasalt-0.png \
                   sfc_aodseasalt-1.png \
                   sfc_aodtot-0.png  \
                   sfc_aodtot-1.png  \
                   sfc_aod-0.png     \
                   sfc_aod-1.png     \
                   h50_ozone-0.png   \
                   h50_ozone-1.png   \
                   pv2_ptemp-0.png   \
                   pv2_ptemp-1.png   \
                   pv2_wind-0.png    \
                   pv2_wind-1.png    \
                   pv2_pres-0.png    \
                   pv2_pres-1.png

    set -A pngs130 sfc_temp-0.png    \
                   sfc_temp-1.png    \
                   sfc_temp-2.png    \
                   sfc_temp-3.png    \
                   sfc_temp-4.png    \
                   sfc_temp-5.png    \
                   sfc_temp-6.png    \
                   sfc_temp-7.png    \
                   850_wind-0.png    \
                   850_wind-1.png    \
                   850_wind-2.png    \
                   850_wind-3.png    \
                   850_wind-4.png    \
                   850_wind-5.png    \
                   850_wind-6.png    \
                   850_wind-7.png    \
                   250_wind-0.png    \
                   250_wind-1.png    \
                   250_wind-2.png    \
                   250_wind-3.png    \
                   250_wind-4.png    \
                   250_wind-5.png    \
                   250_wind-6.png    \
                   250_wind-7.png    \
                   25_wind-0.png     \
                   25_wind-1.png     \
                   25_wind-2.png     \
                   25_wind-3.png     \
                   25_wind-4.png     \
                   25_wind-5.png     \
                   25_wind-6.png     \
                   25_wind-7.png     \
                   20_wind-0.png     \
                   20_wind-1.png     \
                   20_wind-2.png     \
                   20_wind-3.png     \
                   20_wind-4.png     \
                   20_wind-5.png     \
                   20_wind-6.png     \
                   20_wind-7.png     \
                   10_wind-0.png     \
                   10_wind-1.png     \
                   10_wind-2.png     \
                   10_wind-3.png     \
                   10_wind-4.png     \
                   10_wind-5.png     \
                   10_wind-6.png     \
                   10_wind-7.png     \
                   5_wind-0.png      \
                   5_wind-1.png      \
                   5_wind-2.png      \
                   5_wind-3.png      \
                   5_wind-4.png      \
                   5_wind-5.png      \
                   5_wind-6.png      \
                   5_wind-7.png      \
                   850_wmag-0.png    \
                   850_wmag-1.png    \
                   850_wmag-2.png    \
                   850_wmag-3.png    \
                   850_wmag-4.png    \
                   850_wmag-5.png    \
                   850_wmag-6.png    \
                   850_wmag-7.png    \
                   250_wmag-0.png    \
                   250_wmag-1.png    \
                   250_wmag-2.png    \
                   250_wmag-3.png    \
                   250_wmag-4.png    \
                   250_wmag-5.png    \
                   250_wmag-6.png    \
                   250_wmag-7.png    \
                   25_wmag-0.png     \
                   25_wmag-1.png     \
                   25_wmag-2.png     \
                   25_wmag-3.png     \
                   25_wmag-4.png     \
                   25_wmag-5.png     \
                   25_wmag-6.png     \
                   25_wmag-7.png     \
                   20_wmag-0.png     \
                   20_wmag-1.png     \
                   20_wmag-2.png     \
                   20_wmag-3.png     \
                   20_wmag-4.png     \
                   20_wmag-5.png     \
                   20_wmag-6.png     \
                   20_wmag-7.png     \
                   10_wmag-0.png     \
                   10_wmag-1.png     \
                   10_wmag-2.png     \
                   10_wmag-3.png     \
                   10_wmag-4.png     \
                   10_wmag-5.png     \
                   10_wmag-6.png     \
                   10_wmag-7.png     \
                   5_wmag-0.png      \
                   5_wmag-1.png      \
                   5_wmag-2.png      \
                   5_wmag-3.png      \
                   5_wmag-4.png      \
                   5_wmag-5.png      \
                   5_wmag-6.png      \
                   5_wmag-7.png      \
                   sfc_pwtr-0.png    \
                   sfc_pwtr-1.png    \
                   sfc_pwtr-2.png    \
                   sfc_pwtr-3.png    \
                   sfc_pwtr-4.png    \
                   sfc_pwtr-5.png    \
                   sfc_pwtr-6.png    \
                   sfc_pwtr-7.png    \
                   sfc_cwat-0.png    \
                   sfc_cwat-1.png    \
                   sfc_cwat-2.png    \
                   sfc_cwat-3.png    \
                   sfc_cwat-4.png    \
                   sfc_cwat-5.png    \
                   sfc_cwat-6.png    \
                   sfc_cwat-7.png    \
                   sfc_mslp-0.png    \
                   sfc_mslp-1.png    \
                   sfc_mslp-2.png    \
                   sfc_mslp-3.png    \
                   sfc_mslp-4.png    \
                   sfc_mslp-5.png    \
                   sfc_mslp-6.png    \
                   sfc_mslp-7.png    \
                   10_temp-0.png     \
                   10_temp-1.png     \
                   10_temp-2.png     \
                   10_temp-3.png     \
                   10_temp-4.png     \
                   10_temp-5.png     \
                   10_temp-6.png     \
                   10_temp-7.png     \
                   500_temp-0.png    \
                   500_temp-1.png    \
                   500_temp-2.png    \
                   500_temp-3.png    \
                   500_temp-4.png    \
                   500_temp-5.png    \
                   500_temp-6.png    \
                   500_temp-7.png    \
                   700_temp-0.png    \
                   700_temp-1.png    \
                   700_temp-2.png    \
                   700_temp-3.png    \
                   700_temp-4.png    \
                   700_temp-5.png    \
                   700_temp-6.png    \
                   700_temp-7.png    \
                   850_temp-0.png    \
                   850_temp-1.png    \
                   850_temp-2.png    \
                   850_temp-3.png    \
                   850_temp-4.png    \
                   850_temp-5.png    \
                   850_temp-6.png    \
                   850_temp-7.png    \
                   925_temp-0.png    \
                   925_temp-1.png    \
                   925_temp-2.png    \
                   925_temp-3.png    \
                   925_temp-4.png    \
                   925_temp-5.png    \
                   925_temp-6.png    \
                   925_temp-7.png    \
                   500_hgt-0.png     \
                   500_hgt-1.png     \
                   500_hgt-2.png     \
                   500_hgt-3.png     \
                   500_hgt-4.png     \
                   500_hgt-5.png     \
                   500_hgt-6.png     \
                   500_hgt-7.png     \
                   ua_rh-0.png       \
                   ua_rh-1.png       \
                   ua_rh-2.png       \
                   ua_rh-3.png       \
                   ua_rh-4.png       \
                   ua_rh-5.png       \
                   ua_rh-6.png       \
                   ua_rh-7.png       \
                   850_rh-0.png      \
                   850_rh-1.png      \
                   850_rh-2.png      \
                   850_rh-3.png      \
                   850_rh-4.png      \
                   850_rh-5.png      \
                   850_rh-6.png      \
                   850_rh-7.png      \
                   500_vort-0.png    \
                   500_vort-1.png    \
                   500_vort-2.png    \
                   500_vort-3.png    \
                   500_vort-4.png    \
                   500_vort-5.png    \
                   500_vort-6.png    \
                   500_vort-7.png    \
                   700_vvel-0.png    \
                   700_vvel-1.png    \
                   700_vvel-2.png    \
                   700_vvel-3.png    \
                   700_vvel-4.png    \
                   700_vvel-5.png    \
                   700_vvel-6.png    \
                   700_vvel-7.png    \
                   sfc_shtfl-0.png   \
                   sfc_shtfl-1.png   \
                   sfc_shtfl-2.png   \
                   sfc_shtfl-3.png   \
                   sfc_shtfl-4.png   \
                   sfc_shtfl-5.png   \
                   sfc_shtfl-6.png   \
                   sfc_shtfl-7.png   \
                   sfc_lhtfl-0.png   \
                   sfc_lhtfl-1.png   \
                   sfc_lhtfl-2.png   \
                   sfc_lhtfl-3.png   \
                   sfc_lhtfl-4.png   \
                   sfc_lhtfl-5.png   \
                   sfc_lhtfl-6.png   \
                   sfc_lhtfl-7.png   \
                   sfc_dswrf-0.png   \
                   sfc_dswrf-1.png   \
                   sfc_dswrf-2.png   \
                   sfc_dswrf-3.png   \
                   sfc_dswrf-4.png   \
                   sfc_dswrf-5.png   \
                   sfc_dswrf-6.png   \
                   sfc_dswrf-7.png   \
                   sfc_dlwrf-0.png   \
                   sfc_dlwrf-1.png   \
                   sfc_dlwrf-2.png   \
                   sfc_dlwrf-3.png   \
                   sfc_dlwrf-4.png   \
                   sfc_dlwrf-5.png   \
                   sfc_dlwrf-6.png   \
                   sfc_dlwrf-7.png   \
                   sfc_uswrf-0.png   \
                   sfc_uswrf-1.png   \
                   sfc_uswrf-2.png   \
                   sfc_uswrf-3.png   \
                   sfc_uswrf-4.png   \
                   sfc_uswrf-5.png   \
                   sfc_uswrf-6.png   \
                   sfc_uswrf-7.png   \
                   sfc_ulwrf-0.png   \
                   sfc_ulwrf-1.png   \
                   sfc_ulwrf-2.png   \
                   sfc_ulwrf-3.png   \
                   sfc_ulwrf-4.png   \
                   sfc_ulwrf-5.png   \
                   sfc_ulwrf-6.png   \
                   sfc_ulwrf-7.png   \
                   nta_ulwrf-0.png   \
                   nta_ulwrf-1.png   \
                   nta_ulwrf-2.png   \
                   nta_ulwrf-3.png   \
                   nta_ulwrf-4.png   \
                   nta_ulwrf-5.png   \
                   nta_ulwrf-6.png   \
                   nta_ulwrf-7.png   \
                   2m_temp-0.png     \
                   2m_temp-1.png     \
                   2m_temp-2.png     \
                   2m_temp-3.png     \
                   2m_temp-4.png     \
                   2m_temp-5.png     \
                   2m_temp-6.png     \
                   2m_temp-7.png     \
                   2ds_temp-0.png    \
                   2ds_temp-1.png    \
                   2ds_temp-2.png    \
                   2ds_temp-3.png    \
                   2ds_temp-4.png    \
                   2ds_temp-5.png    \
                   2ds_temp-6.png    \
                   2ds_temp-7.png    \
                   2m_dewp-0.png     \
                   2m_dewp-1.png     \
                   2m_dewp-2.png     \
                   2m_dewp-3.png     \
                   2m_dewp-4.png     \
                   2m_dewp-5.png     \
                   2m_dewp-6.png     \
                   2m_dewp-7.png     \
                   10m_wind-0.png    \
                   10m_wind-1.png    \
                   10m_wind-2.png    \
                   10m_wind-3.png    \
                   10m_wind-4.png    \
                   10m_wind-5.png    \
                   10m_wind-6.png    \
                   10m_wind-7.png    \
                   80m_wind-0.png    \
                   80m_wind-1.png    \
                   80m_wind-2.png    \
                   80m_wind-3.png    \
                   80m_wind-4.png    \
                   80m_wind-5.png    \
                   80m_wind-6.png    \
                   80m_wind-7.png    \
                   sfc_totp-0.png    \
                   sfc_totp-1.png    \
                   sfc_totp-2.png    \
                   sfc_totp-3.png    \
                   sfc_totp-4.png    \
                   sfc_totp-5.png    \
                   sfc_totp-6.png    \
                   sfc_totp-7.png    \
                   12h_totp-0.png    \
                   12h_totp-1.png    \
                   12h_totp-2.png    \
                   12h_totp-3.png    \
                   12h_totp-4.png    \
                   12h_totp-5.png    \
                   12h_totp-6.png    \
                   12h_totp-7.png    \
                   24h_totp-0.png    \
                   24h_totp-1.png    \
                   24h_totp-2.png    \
                   24h_totp-3.png    \
                   24h_totp-4.png    \
                   24h_totp-5.png    \
                   24h_totp-6.png    \
                   24h_totp-7.png    \
                   sfc_acp-0.png     \
                   sfc_acp-1.png     \
                   sfc_acp-2.png     \
                   sfc_acp-3.png     \
                   sfc_acp-4.png     \
                   sfc_acp-5.png     \
                   sfc_acp-6.png     \
                   sfc_acp-7.png     \
                   esbl_hvyacp-0.png \
                   esbl_hvyacp-1.png \
                   esbl_hvyacp-2.png \
                   esbl_hvyacp-3.png \
                   esbl_hvyacp-4.png \
                   esbl_hvyacp-5.png \
                   esbl_hvyacp-6.png \
                   esbl_hvyacp-7.png \
                   sfc_acpcp-0.png   \
                   sfc_acpcp-1.png   \
                   sfc_acpcp-2.png   \
                   sfc_acpcp-3.png   \
                   sfc_acpcp-4.png   \
                   sfc_acpcp-5.png   \
                   sfc_acpcp-6.png   \
                   sfc_acpcp-7.png   \
                   sfc_weasd-0.png   \
                   sfc_weasd-1.png   \
                   sfc_weasd-2.png   \
                   sfc_weasd-3.png   \
                   sfc_weasd-4.png   \
                   sfc_weasd-5.png   \
                   sfc_weasd-6.png   \
                   sfc_weasd-7.png   \
                   sfc_acsnw-0.png   \
                   sfc_acsnw-1.png   \
                   sfc_acsnw-2.png   \
                   sfc_acsnw-3.png   \
                   sfc_acsnw-4.png   \
                   sfc_acsnw-5.png   \
                   sfc_acsnw-6.png   \
                   sfc_acsnw-7.png   \
                   sfc_totsn-0.png   \
                   sfc_totsn-1.png   \
                   sfc_totsn-2.png   \
                   sfc_totsn-3.png   \
                   sfc_totsn-4.png   \
                   sfc_totsn-5.png   \
                   sfc_totsn-6.png   \
                   sfc_totsn-7.png   \
                   12h_totsn-0.png   \
                   12h_totsn-1.png   \
                   12h_totsn-2.png   \
                   12h_totsn-3.png   \
                   12h_totsn-4.png   \
                   12h_totsn-5.png   \
                   12h_totsn-6.png   \
                   12h_totsn-7.png   \
                   24h_totsn-0.png   \
                   24h_totsn-1.png   \
                   24h_totsn-2.png   \
                   24h_totsn-3.png   \
                   24h_totsn-4.png   \
                   24h_totsn-5.png   \
                   24h_totsn-6.png   \
                   24h_totsn-7.png   \
                   ua_ceil-0.png     \
                   ua_ceil-1.png     \
                   ua_ceil-2.png     \
                   ua_ceil-3.png     \
                   ua_ceil-4.png     \
                   ua_ceil-5.png     \
                   ua_ceil-6.png     \
                   ua_ceil-7.png     \
                   ua_ctop-0.png     \
                   ua_ctop-1.png     \
                   ua_ctop-2.png     \
                   ua_ctop-3.png     \
                   ua_ctop-4.png     \
                   ua_ctop-5.png     \
                   ua_ctop-6.png     \
                   ua_ctop-7.png     \
                   sfc_rhpw-0.png    \
                   sfc_rhpw-1.png    \
                   sfc_rhpw-2.png    \
                   sfc_rhpw-3.png    \
                   sfc_rhpw-4.png    \
                   sfc_rhpw-5.png    \
                   sfc_rhpw-6.png    \
                   sfc_rhpw-7.png    \
                   sfc_fd-0.png      \
                   sfc_fd-1.png      \
                   sfc_fd-2.png      \
                   sfc_fd-3.png      \
                   sfc_fd-4.png      \
                   sfc_fd-5.png      \
                   sfc_fd-6.png      \
                   sfc_fd-7.png      \
                   sfc_bc-0.png      \
                   sfc_bc-1.png      \
                   sfc_bc-2.png      \
                   sfc_bc-3.png      \
                   sfc_bc-4.png      \
                   sfc_bc-5.png      \
                   sfc_bc-6.png      \
                   sfc_bc-7.png      \
                   sfc_oc-0.png      \
                   sfc_oc-1.png      \
                   sfc_oc-2.png      \
                   sfc_oc-3.png      \
                   sfc_oc-4.png      \
                   sfc_oc-5.png      \
                   sfc_oc-6.png      \
                   sfc_oc-7.png      \
                   sfc_sulf-0.png    \
                   sfc_sulf-1.png    \
                   sfc_sulf-2.png    \
                   sfc_sulf-3.png    \
                   sfc_sulf-4.png    \
                   sfc_sulf-5.png    \
                   sfc_sulf-6.png    \
                   sfc_sulf-7.png    \
                   sfc_seasalt-0.png \
                   sfc_seasalt-1.png \
                   sfc_seasalt-2.png \
                   sfc_seasalt-3.png \
                   sfc_seasalt-4.png \
                   sfc_seasalt-5.png \
                   sfc_seasalt-6.png \
                   sfc_seasalt-7.png \
                   sfc_PM10-0.png    \
                   sfc_PM10-1.png    \
                   sfc_PM10-2.png    \
                   sfc_PM10-3.png    \
                   sfc_PM10-4.png    \
                   sfc_PM10-5.png    \
                   sfc_PM10-6.png    \
                   sfc_PM10-7.png    \
                   sfc_PM25-0.png    \
                   sfc_PM25-1.png    \
                   sfc_PM25-2.png    \
                   sfc_PM25-3.png    \
                   sfc_PM25-4.png    \
                   sfc_PM25-5.png    \
                   sfc_PM25-6.png    \
                   sfc_PM25-7.png    \
                   col_fd-0.png      \
                   col_fd-1.png      \
                   col_fd-2.png      \
                   col_fd-3.png      \
                   col_fd-4.png      \
                   col_fd-5.png      \
                   col_fd-6.png      \
                   col_fd-7.png      \
                   col_bc-0.png      \
                   col_bc-1.png      \
                   col_bc-2.png      \
                   col_bc-3.png      \
                   col_bc-4.png      \
                   col_bc-5.png      \
                   col_bc-6.png      \
                   col_bc-7.png      \
                   col_oc-0.png      \
                   col_oc-1.png      \
                   col_oc-2.png      \
                   col_oc-3.png      \
                   col_oc-4.png      \
                   col_oc-5.png      \
                   col_oc-6.png      \
                   col_oc-7.png      \
                   col_sulf-0.png    \
                   col_sulf-1.png    \
                   col_sulf-2.png    \
                   col_sulf-3.png    \
                   col_sulf-4.png    \
                   col_sulf-5.png    \
                   col_sulf-6.png    \
                   col_sulf-7.png    \
                   col_seasalt-0.png \
                   col_seasalt-1.png \
                   col_seasalt-2.png \
                   col_seasalt-3.png \
                   col_seasalt-4.png \
                   col_seasalt-5.png \
                   col_seasalt-6.png \
                   col_seasalt-7.png \
                   col_PM10-0.png    \
                   col_PM10-1.png    \
                   col_PM10-2.png    \
                   col_PM10-3.png    \
                   col_PM10-4.png    \
                   col_PM10-5.png    \
                   col_PM10-6.png    \
                   col_PM10-7.png    \
                   col_PM25-0.png    \
                   col_PM25-1.png    \
                   col_PM25-2.png    \
                   col_PM25-3.png    \
                   col_PM25-4.png    \
                   col_PM25-5.png    \
                   col_PM25-6.png    \
                   col_PM25-7.png    \
                   col_tozne-0.png   \
                   col_tozne-1.png   \
                   col_tozne-2.png   \
                   col_tozne-3.png   \
                   col_tozne-4.png   \
                   col_tozne-5.png   \
                   col_tozne-6.png   \
                   col_tozne-7.png   \
                   sfc_aodfd-0.png   \
                   sfc_aodfd-1.png   \
                   sfc_aodfd-2.png   \
                   sfc_aodfd-3.png   \
                   sfc_aodfd-4.png   \
                   sfc_aodfd-5.png   \
                   sfc_aodfd-6.png   \
                   sfc_aodfd-7.png   \
                   sfc_aodbc-0.png   \
                   sfc_aodbc-1.png   \
                   sfc_aodbc-2.png   \
                   sfc_aodbc-3.png   \
                   sfc_aodbc-4.png   \
                   sfc_aodbc-5.png   \
                   sfc_aodbc-6.png   \
                   sfc_aodbc-7.png   \
                   sfc_aodoc-0.png   \
                   sfc_aodoc-1.png   \
                   sfc_aodoc-2.png   \
                   sfc_aodoc-3.png   \
                   sfc_aodoc-4.png   \
                   sfc_aodoc-5.png   \
                   sfc_aodoc-6.png   \
                   sfc_aodoc-7.png   \
                   sfc_aodsulf-0.png \
                   sfc_aodsulf-1.png \
                   sfc_aodsulf-2.png \
                   sfc_aodsulf-3.png \
                   sfc_aodsulf-4.png \
                   sfc_aodsulf-5.png \
                   sfc_aodsulf-6.png \
                   sfc_aodsulf-7.png \
                   sfc_aodseasalt-0.png \
                   sfc_aodseasalt-1.png \
                   sfc_aodseasalt-2.png \
                   sfc_aodseasalt-3.png \
                   sfc_aodseasalt-4.png \
                   sfc_aodseasalt-5.png \
                   sfc_aodseasalt-6.png \
                   sfc_aodseasalt-7.png \
                   sfc_aodtot-0.png  \
                   sfc_aodtot-1.png  \
                   sfc_aodtot-2.png  \
                   sfc_aodtot-3.png  \
                   sfc_aodtot-4.png  \
                   sfc_aodtot-5.png  \
                   sfc_aodtot-6.png  \
                   sfc_aodtot-7.png  \
                   sfc_aod-0.png     \
                   sfc_aod-1.png     \
                   sfc_aod-2.png     \
                   sfc_aod-3.png     \
                   sfc_aod-4.png     \
                   sfc_aod-5.png     \
                   sfc_aod-6.png     \
                   sfc_aod-7.png     \
                   h50_ozone-0.png   \
                   h50_ozone-1.png   \
                   h50_ozone-2.png   \
                   h50_ozone-3.png   \
                   h50_ozone-4.png   \
                   h50_ozone-5.png   \
                   h50_ozone-6.png   \
                   h50_ozone-7.png   \
                   pv2_ptemp-0.png   \
                   pv2_ptemp-1.png   \
                   pv2_ptemp-2.png   \
                   pv2_ptemp-3.png   \
                   pv2_ptemp-4.png   \
                   pv2_ptemp-5.png   \
                   pv2_ptemp-6.png   \
                   pv2_ptemp-7.png   \
                   pv2_wind-0.png    \
                   pv2_wind-1.png    \
                   pv2_wind-2.png    \
                   pv2_wind-3.png    \
                   pv2_wind-4.png    \
                   pv2_wind-5.png    \
                   pv2_wind-6.png    \
                   pv2_wind-7.png    \
                   pv2_pres-0.png    \
                   pv2_pres-1.png    \
                   pv2_pres-2.png    \
                   pv2_pres-3.png    \
                   pv2_pres-4.png    \
                   pv2_pres-5.png    \
                   pv2_pres-6.png    \
                   pv2_pres-7.png

    set -A pngs174 sfc_temp-0.png    \
                   sfc_temp-1.png    \
                   sfc_temp-2.png    \
                   sfc_temp-3.png    \
                   sfc_temp-4.png    \
                   sfc_temp-5.png    \
                   850_wind-0.png    \
                   850_wind-1.png    \
                   850_wind-2.png    \
                   850_wind-3.png    \
                   850_wind-4.png    \
                   850_wind-5.png    \
                   250_wind-0.png    \
                   250_wind-1.png    \
                   250_wind-2.png    \
                   250_wind-3.png    \
                   250_wind-4.png    \
                   250_wind-5.png    \
                   25_wind-0.png     \
                   25_wind-1.png     \
                   25_wind-2.png     \
                   25_wind-3.png     \
                   25_wind-4.png     \
                   25_wind-5.png     \
                   20_wind-0.png     \
                   20_wind-1.png     \
                   20_wind-2.png     \
                   20_wind-3.png     \
                   20_wind-4.png     \
                   20_wind-5.png     \
                   10_wind-0.png     \
                   10_wind-1.png     \
                   10_wind-2.png     \
                   10_wind-3.png     \
                   10_wind-4.png     \
                   10_wind-5.png     \
                   5_wind-0.png      \
                   5_wind-1.png      \
                   5_wind-2.png      \
                   5_wind-3.png      \
                   5_wind-4.png      \
                   5_wind-5.png      \
                   850_wmag-0.png    \
                   850_wmag-1.png    \
                   850_wmag-2.png    \
                   850_wmag-3.png    \
                   850_wmag-4.png    \
                   850_wmag-5.png    \
                   250_wmag-0.png    \
                   250_wmag-1.png    \
                   250_wmag-2.png    \
                   250_wmag-3.png    \
                   250_wmag-4.png    \
                   250_wmag-5.png    \
                   25_wmag-0.png     \
                   25_wmag-1.png     \
                   25_wmag-2.png     \
                   25_wmag-3.png     \
                   25_wmag-4.png     \
                   25_wmag-5.png     \
                   20_wmag-0.png     \
                   20_wmag-1.png     \
                   20_wmag-2.png     \
                   20_wmag-3.png     \
                   20_wmag-4.png     \
                   20_wmag-5.png     \
                   10_wmag-0.png     \
                   10_wmag-1.png     \
                   10_wmag-2.png     \
                   10_wmag-3.png     \
                   10_wmag-4.png     \
                   10_wmag-5.png     \
                   5_wmag-0.png      \
                   5_wmag-1.png      \
                   5_wmag-2.png      \
                   5_wmag-3.png      \
                   5_wmag-4.png      \
                   5_wmag-5.png      \
                   sfc_pwtr-0.png    \
                   sfc_pwtr-1.png    \
                   sfc_pwtr-2.png    \
                   sfc_pwtr-3.png    \
                   sfc_pwtr-4.png    \
                   sfc_pwtr-5.png    \
                   sfc_cwat-0.png    \
                   sfc_cwat-1.png    \
                   sfc_cwat-2.png    \
                   sfc_cwat-3.png    \
                   sfc_cwat-4.png    \
                   sfc_cwat-5.png    \
                   sfc_mslp-0.png    \
                   sfc_mslp-1.png    \
                   sfc_mslp-2.png    \
                   sfc_mslp-3.png    \
                   sfc_mslp-4.png    \
                   sfc_mslp-5.png    \
                   10_temp-0.png     \
                   10_temp-1.png     \
                   10_temp-2.png     \
                   10_temp-3.png     \
                   10_temp-4.png     \
                   10_temp-5.png     \
                   500_temp-0.png    \
                   500_temp-1.png    \
                   500_temp-2.png    \
                   500_temp-3.png    \
                   500_temp-4.png    \
                   500_temp-5.png    \
                   700_temp-0.png    \
                   700_temp-1.png    \
                   700_temp-2.png    \
                   700_temp-3.png    \
                   700_temp-4.png    \
                   700_temp-5.png    \
                   850_temp-0.png    \
                   850_temp-1.png    \
                   850_temp-2.png    \
                   850_temp-3.png    \
                   850_temp-4.png    \
                   850_temp-5.png    \
                   925_temp-0.png    \
                   925_temp-1.png    \
                   925_temp-2.png    \
                   925_temp-3.png    \
                   925_temp-4.png    \
                   925_temp-5.png    \
                   500_hgt-0.png     \
                   500_hgt-1.png     \
                   500_hgt-2.png     \
                   500_hgt-3.png     \
                   500_hgt-4.png     \
                   500_hgt-5.png     \
                   ua_rh-0.png       \
                   ua_rh-1.png       \
                   ua_rh-2.png       \
                   ua_rh-3.png       \
                   ua_rh-4.png       \
                   ua_rh-5.png       \
                   850_rh-0.png      \
                   850_rh-1.png      \
                   850_rh-2.png      \
                   850_rh-3.png      \
                   850_rh-4.png      \
                   850_rh-5.png      \
                   500_vort-0.png    \
                   500_vort-1.png    \
                   500_vort-2.png    \
                   500_vort-3.png    \
                   500_vort-4.png    \
                   500_vort-5.png    \
                   700_vvel-0.png    \
                   700_vvel-1.png    \
                   700_vvel-2.png    \
                   700_vvel-3.png    \
                   700_vvel-4.png    \
                   700_vvel-5.png    \
                   sfc_shtfl-0.png   \
                   sfc_shtfl-1.png   \
                   sfc_shtfl-2.png   \
                   sfc_shtfl-3.png   \
                   sfc_shtfl-4.png   \
                   sfc_shtfl-5.png   \
                   sfc_lhtfl-0.png   \
                   sfc_lhtfl-1.png   \
                   sfc_lhtfl-2.png   \
                   sfc_lhtfl-3.png   \
                   sfc_lhtfl-4.png   \
                   sfc_lhtfl-5.png   \
                   sfc_dswrf-0.png   \
                   sfc_dswrf-1.png   \
                   sfc_dswrf-2.png   \
                   sfc_dswrf-3.png   \
                   sfc_dswrf-4.png   \
                   sfc_dswrf-5.png   \
                   sfc_dlwrf-0.png   \
                   sfc_dlwrf-1.png   \
                   sfc_dlwrf-2.png   \
                   sfc_dlwrf-3.png   \
                   sfc_dlwrf-4.png   \
                   sfc_dlwrf-5.png   \
                   sfc_uswrf-0.png   \
                   sfc_uswrf-1.png   \
                   sfc_uswrf-2.png   \
                   sfc_uswrf-3.png   \
                   sfc_uswrf-4.png   \
                   sfc_uswrf-5.png   \
                   sfc_ulwrf-0.png   \
                   sfc_ulwrf-1.png   \
                   sfc_ulwrf-2.png   \
                   sfc_ulwrf-3.png   \
                   sfc_ulwrf-4.png   \
                   sfc_ulwrf-5.png   \
                   nta_ulwrf-0.png   \
                   nta_ulwrf-1.png   \
                   nta_ulwrf-2.png   \
                   nta_ulwrf-3.png   \
                   nta_ulwrf-4.png   \
                   nta_ulwrf-5.png   \
                   2m_temp-0.png     \
                   2m_temp-1.png     \
                   2m_temp-2.png     \
                   2m_temp-3.png     \
                   2m_temp-4.png     \
                   2m_temp-5.png     \
                   2ds_temp-0.png    \
                   2ds_temp-1.png    \
                   2ds_temp-2.png    \
                   2ds_temp-3.png    \
                   2ds_temp-4.png    \
                   2ds_temp-5.png    \
                   2m_dewp-0.png     \
                   2m_dewp-1.png     \
                   2m_dewp-2.png     \
                   2m_dewp-3.png     \
                   2m_dewp-4.png     \
                   2m_dewp-5.png     \
                   10m_wind-0.png    \
                   10m_wind-1.png    \
                   10m_wind-2.png    \
                   10m_wind-3.png    \
                   10m_wind-4.png    \
                   10m_wind-5.png    \
                   80m_wind-0.png    \
                   80m_wind-1.png    \
                   80m_wind-2.png    \
                   80m_wind-3.png    \
                   80m_wind-4.png    \
                   80m_wind-5.png    \
                   sfc_totp-0.png    \
                   sfc_totp-1.png    \
                   sfc_totp-2.png    \
                   sfc_totp-3.png    \
                   sfc_totp-4.png    \
                   sfc_totp-5.png    \
                   12h_totp-0.png    \
                   12h_totp-1.png    \
                   12h_totp-2.png    \
                   12h_totp-3.png    \
                   12h_totp-4.png    \
                   12h_totp-5.png    \
                   24h_totp-0.png    \
                   24h_totp-1.png    \
                   24h_totp-2.png    \
                   24h_totp-3.png    \
                   24h_totp-4.png    \
                   24h_totp-5.png    \
                   sfc_acp-0.png     \
                   sfc_acp-1.png     \
                   sfc_acp-2.png     \
                   sfc_acp-3.png     \
                   sfc_acp-4.png     \
                   sfc_acp-5.png     \
                   esbl_hvyacp-0.png \
                   esbl_hvyacp-1.png \
                   esbl_hvyacp-2.png \
                   esbl_hvyacp-3.png \
                   esbl_hvyacp-4.png \
                   esbl_hvyacp-5.png \
                   sfc_acpcp-0.png   \
                   sfc_acpcp-1.png   \
                   sfc_acpcp-2.png   \
                   sfc_acpcp-3.png   \
                   sfc_acpcp-4.png   \
                   sfc_acpcp-5.png   \
                   sfc_weasd-0.png   \
                   sfc_weasd-1.png   \
                   sfc_weasd-2.png   \
                   sfc_weasd-3.png   \
                   sfc_weasd-4.png   \
                   sfc_weasd-5.png   \
                   sfc_acsnw-0.png   \
                   sfc_acsnw-1.png   \
                   sfc_acsnw-2.png   \
                   sfc_acsnw-3.png   \
                   sfc_acsnw-4.png   \
                   sfc_acsnw-5.png   \
                   sfc_totsn-0.png   \
                   sfc_totsn-1.png   \
                   sfc_totsn-2.png   \
                   sfc_totsn-3.png   \
                   sfc_totsn-4.png   \
                   sfc_totsn-5.png   \
                   12h_totsn-0.png   \
                   12h_totsn-1.png   \
                   12h_totsn-2.png   \
                   12h_totsn-3.png   \
                   12h_totsn-4.png   \
                   12h_totsn-5.png   \
                   24h_totsn-0.png   \
                   24h_totsn-1.png   \
                   24h_totsn-2.png   \
                   24h_totsn-3.png   \
                   24h_totsn-4.png   \
                   24h_totsn-5.png   \
                   ua_ceil-0.png     \
                   ua_ceil-1.png     \
                   ua_ceil-2.png     \
                   ua_ceil-3.png     \
                   ua_ceil-4.png     \
                   ua_ceil-5.png     \
                   ua_ctop-0.png     \
                   ua_ctop-1.png     \
                   ua_ctop-2.png     \
                   ua_ctop-3.png     \
                   ua_ctop-4.png     \
                   ua_ctop-5.png     \
                   sfc_rhpw-0.png    \
                   sfc_rhpw-1.png    \
                   sfc_rhpw-2.png    \
                   sfc_rhpw-3.png    \
                   sfc_rhpw-4.png    \
                   sfc_rhpw-5.png    \
                   sfc_fd-0.png      \
                   sfc_fd-1.png      \
                   sfc_fd-2.png      \
                   sfc_fd-3.png      \
                   sfc_fd-4.png      \
                   sfc_fd-5.png      \
                   sfc_bc-0.png      \
                   sfc_bc-1.png      \
                   sfc_bc-2.png      \
                   sfc_bc-3.png      \
                   sfc_bc-4.png      \
                   sfc_bc-5.png      \
                   sfc_oc-0.png      \
                   sfc_oc-1.png      \
                   sfc_oc-2.png      \
                   sfc_oc-3.png      \
                   sfc_oc-4.png      \
                   sfc_oc-5.png      \
                   sfc_sulf-0.png    \
                   sfc_sulf-1.png    \
                   sfc_sulf-2.png    \
                   sfc_sulf-3.png    \
                   sfc_sulf-4.png    \
                   sfc_sulf-5.png    \
                   sfc_seasalt-0.png \
                   sfc_seasalt-1.png \
                   sfc_seasalt-2.png \
                   sfc_seasalt-3.png \
                   sfc_seasalt-4.png \
                   sfc_seasalt-5.png \
                   sfc_PM10-0.png    \
                   sfc_PM10-1.png    \
                   sfc_PM10-2.png    \
                   sfc_PM10-3.png    \
                   sfc_PM10-4.png    \
                   sfc_PM10-5.png    \
                   sfc_PM25-0.png    \
                   sfc_PM25-1.png    \
                   sfc_PM25-2.png    \
                   sfc_PM25-3.png    \
                   sfc_PM25-4.png    \
                   sfc_PM25-5.png    \
                   col_fd-0.png      \
                   col_fd-1.png      \
                   col_fd-2.png      \
                   col_fd-3.png      \
                   col_fd-4.png      \
                   col_fd-5.png      \
                   col_bc-0.png      \
                   col_bc-1.png      \
                   col_bc-2.png      \
                   col_bc-3.png      \
                   col_bc-4.png      \
                   col_bc-5.png      \
                   col_oc-0.png      \
                   col_oc-1.png      \
                   col_oc-2.png      \
                   col_oc-3.png      \
                   col_oc-4.png      \
                   col_oc-5.png      \
                   col_sulf-0.png    \
                   col_sulf-1.png    \
                   col_sulf-2.png    \
                   col_sulf-3.png    \
                   col_sulf-4.png    \
                   col_sulf-5.png    \
                   col_seasalt-0.png \
                   col_seasalt-1.png \
                   col_seasalt-2.png \
                   col_seasalt-3.png \
                   col_seasalt-4.png \
                   col_seasalt-5.png \
                   col_PM10-0.png    \
                   col_PM10-1.png    \
                   col_PM10-2.png    \
                   col_PM10-3.png    \
                   col_PM10-4.png    \
                   col_PM10-5.png    \
                   col_PM25-0.png    \
                   col_PM25-1.png    \
                   col_PM25-2.png    \
                   col_PM25-3.png    \
                   col_PM25-4.png    \
                   col_PM25-5.png    \
                   col_tozne-0.png   \
                   col_tozne-1.png   \
                   col_tozne-2.png   \
                   col_tozne-3.png   \
                   col_tozne-4.png   \
                   col_tozne-5.png   \
                   sfc_aodfd-0.png   \
                   sfc_aodfd-1.png   \
                   sfc_aodfd-2.png   \
                   sfc_aodfd-3.png   \
                   sfc_aodfd-4.png   \
                   sfc_aodfd-5.png   \
                   sfc_aodbc-0.png   \
                   sfc_aodbc-1.png   \
                   sfc_aodbc-2.png   \
                   sfc_aodbc-3.png   \
                   sfc_aodbc-4.png   \
                   sfc_aodbc-5.png   \
                   sfc_aodoc-0.png   \
                   sfc_aodoc-1.png   \
                   sfc_aodoc-2.png   \
                   sfc_aodoc-3.png   \
                   sfc_aodoc-4.png   \
                   sfc_aodoc-5.png   \
                   sfc_aodsulf-0.png \
                   sfc_aodsulf-1.png \
                   sfc_aodsulf-2.png \
                   sfc_aodsulf-3.png \
                   sfc_aodsulf-4.png \
                   sfc_aodsulf-5.png \
                   sfc_aodseasalt-0.png \
                   sfc_aodseasalt-1.png \
                   sfc_aodseasalt-2.png \
                   sfc_aodseasalt-3.png \
                   sfc_aodseasalt-4.png \
                   sfc_aodseasalt-5.png \
                   sfc_aodtot-0.png  \
                   sfc_aodtot-1.png  \
                   sfc_aodtot-2.png  \
                   sfc_aodtot-3.png  \
                   sfc_aodtot-4.png  \
                   sfc_aodtot-5.png  \
                   sfc_aod-0.png     \
                   sfc_aod-1.png     \
                   sfc_aod-2.png     \
                   sfc_aod-3.png     \
                   sfc_aod-4.png     \
                   sfc_aod-5.png     \
                   h50_ozone-0.png   \
                   h50_ozone-1.png   \
                   h50_ozone-2.png   \
                   h50_ozone-3.png   \
                   h50_ozone-4.png   \
                   h50_ozone-5.png   \
                   pv2_ptemp-0.png   \
                   pv2_ptemp-1.png   \
                   pv2_ptemp-2.png   \
                   pv2_ptemp-3.png   \
                   pv2_ptemp-4.png   \
                   pv2_ptemp-5.png   \
                   pv2_wind-0.png    \
                   pv2_wind-1.png    \
                   pv2_wind-2.png    \
                   pv2_wind-3.png    \
                   pv2_wind-4.png    \
                   pv2_wind-5.png    \
                   pv2_pres-0.png    \
                   pv2_pres-1.png    \
                   pv2_pres-2.png    \
                   pv2_pres-3.png    \
                   pv2_pres-4.png    \
                   pv2_pres-5.png

    set -A pngs242 sfc_temp-0.png    \
                   sfc_temp-1.png    \
                   sfc_temp-2.png    \
                   850_wind-0.png    \
                   850_wind-1.png    \
                   850_wind-2.png    \
                   250_wind-0.png    \
                   250_wind-1.png    \
                   250_wind-2.png    \
                   25_wind-0.png     \
                   25_wind-1.png     \
                   25_wind-2.png     \
                   20_wind-0.png     \
                   20_wind-1.png     \
                   20_wind-2.png     \
                   10_wind-0.png     \
                   10_wind-1.png     \
                   10_wind-2.png     \
                   5_wind-0.png      \
                   5_wind-1.png      \
                   5_wind-2.png      \
                   850_wmag-0.png    \
                   850_wmag-1.png    \
                   850_wmag-2.png    \
                   250_wmag-0.png    \
                   250_wmag-1.png    \
                   250_wmag-2.png    \
                   25_wmag-0.png     \
                   25_wmag-1.png     \
                   25_wmag-2.png     \
                   20_wmag-0.png     \
                   20_wmag-1.png     \
                   20_wmag-2.png     \
                   10_wmag-0.png     \
                   10_wmag-1.png     \
                   10_wmag-2.png     \
                   5_wmag-0.png      \
                   5_wmag-1.png      \
                   5_wmag-2.png      \
                   sfc_pwtr-0.png    \
                   sfc_pwtr-1.png    \
                   sfc_pwtr-2.png    \
                   sfc_cwat-0.png    \
                   sfc_cwat-1.png    \
                   sfc_cwat-2.png    \
                   sfc_mslp-0.png    \
                   sfc_mslp-1.png    \
                   sfc_mslp-2.png    \
                   10_temp-0.png     \
                   10_temp-1.png     \
                   10_temp-2.png     \
                   500_temp-0.png    \
                   500_temp-1.png    \
                   500_temp-2.png    \
                   700_temp-0.png    \
                   700_temp-1.png    \
                   700_temp-2.png    \
                   850_temp-0.png    \
                   850_temp-1.png    \
                   850_temp-2.png    \
                   925_temp-0.png    \
                   925_temp-1.png    \
                   925_temp-2.png    \
                   500_hgt-0.png     \
                   500_hgt-1.png     \
                   500_hgt-2.png     \
                   ua_rh-0.png       \
                   ua_rh-1.png       \
                   ua_rh-2.png       \
                   850_rh-0.png      \
                   850_rh-1.png      \
                   850_rh-2.png      \
                   500_vort-0.png    \
                   500_vort-1.png    \
                   500_vort-2.png    \
                   700_vvel-0.png    \
                   700_vvel-1.png    \
                   700_vvel-2.png    \
                   sfc_shtfl-0.png   \
                   sfc_shtfl-1.png   \
                   sfc_shtfl-2.png   \
                   sfc_lhtfl-0.png   \
                   sfc_lhtfl-1.png   \
                   sfc_lhtfl-2.png   \
                   sfc_dswrf-0.png   \
                   sfc_dswrf-1.png   \
                   sfc_dswrf-2.png   \
                   sfc_dlwrf-0.png   \
                   sfc_dlwrf-1.png   \
                   sfc_dlwrf-2.png   \
                   sfc_uswrf-0.png   \
                   sfc_uswrf-1.png   \
                   sfc_uswrf-2.png   \
                   sfc_ulwrf-0.png   \
                   sfc_ulwrf-1.png   \
                   sfc_ulwrf-2.png   \
                   nta_ulwrf-0.png   \
                   nta_ulwrf-1.png   \
                   nta_ulwrf-2.png   \
                   2m_temp-0.png     \
                   2m_temp-1.png     \
                   2m_temp-2.png     \
                   2ds_temp-0.png    \
                   2ds_temp-1.png    \
                   2ds_temp-2.png    \
                   2m_dewp-0.png     \
                   2m_dewp-1.png     \
                   2m_dewp-2.png     \
                   10m_wind-0.png    \
                   10m_wind-1.png    \
                   10m_wind-2.png    \
                   80m_wind-0.png    \
                   80m_wind-1.png    \
                   80m_wind-2.png    \
                   sfc_totp-0.png    \
                   sfc_totp-1.png    \
                   sfc_totp-2.png    \
                   12h_totp-0.png    \
                   12h_totp-1.png    \
                   12h_totp-2.png    \
                   24h_totp-0.png    \
                   24h_totp-1.png    \
                   24h_totp-2.png    \
                   sfc_acp-0.png     \
                   sfc_acp-1.png     \
                   sfc_acp-2.png     \
                   esbl_hvyacp-0.png \
                   esbl_hvyacp-1.png \
                   esbl_hvyacp-2.png \
                   sfc_acpcp-0.png   \
                   sfc_acpcp-1.png   \
                   sfc_acpcp-2.png   \
                   sfc_weasd-0.png   \
                   sfc_weasd-1.png   \
                   sfc_weasd-2.png   \
                   sfc_acsnw-0.png   \
                   sfc_acsnw-1.png   \
                   sfc_acsnw-2.png   \
                   sfc_totsn-0.png   \
                   sfc_totsn-1.png   \
                   sfc_totsn-2.png   \
                   12h_totsn-0.png   \
                   12h_totsn-1.png   \
                   12h_totsn-2.png   \
                   24h_totsn-0.png   \
                   24h_totsn-1.png   \
                   24h_totsn-2.png   \
                   ua_ceil-0.png     \
                   ua_ceil-1.png     \
                   ua_ceil-2.png     \
                   ua_ctop-0.png     \
                   ua_ctop-1.png     \
                   ua_ctop-2.png     \
                   sfc_rhpw-0.png    \
                   sfc_rhpw-1.png    \
                   sfc_rhpw-2.png    \
                   sfc_fd-0.png      \
                   sfc_fd-1.png      \
                   sfc_fd-2.png      \
                   sfc_bc-0.png      \
                   sfc_bc-1.png      \
                   sfc_bc-2.png      \
                   sfc_oc-0.png      \
                   sfc_oc-1.png      \
                   sfc_oc-2.png      \
                   sfc_sulf-0.png    \
                   sfc_sulf-1.png    \
                   sfc_sulf-2.png    \
                   sfc_seasalt-0.png \
                   sfc_seasalt-1.png \
                   sfc_seasalt-2.png \
                   sfc_PM10-0.png    \
                   sfc_PM10-1.png    \
                   sfc_PM10-2.png    \
                   sfc_PM25-0.png    \
                   sfc_PM25-1.png    \
                   sfc_PM25-2.png    \
                   col_fd-0.png      \
                   col_fd-1.png      \
                   col_fd-2.png      \
                   col_bc-0.png      \
                   col_bc-1.png      \
                   col_bc-2.png      \
                   col_oc-0.png      \
                   col_oc-1.png      \
                   col_oc-2.png      \
                   col_sulf-0.png    \
                   col_sulf-1.png    \
                   col_sulf-2.png    \
                   col_seasalt-0.png \
                   col_seasalt-1.png \
                   col_seasalt-2.png \
                   col_PM10-0.png    \
                   col_PM10-1.png    \
                   col_PM10-2.png    \
                   col_PM25-0.png    \
                   col_PM25-1.png    \
                   col_PM25-2.png    \
                   col_tozne-0.png   \
                   col_tozne-1.png   \
                   col_tozne-2.png   \
                   sfc_aodfd-0.png   \
                   sfc_aodfd-1.png   \
                   sfc_aodfd-2.png   \
                   sfc_aodbc-0.png   \
                   sfc_aodbc-1.png   \
                   sfc_aodbc-2.png   \
                   sfc_aodoc-0.png   \
                   sfc_aodoc-1.png   \
                   sfc_aodoc-2.png   \
                   sfc_aodsulf-0.png \
                   sfc_aodsulf-1.png \
                   sfc_aodsulf-2.png \
                   sfc_aodseasalt-0.png \
                   sfc_aodseasalt-1.png \
                   sfc_aodseasalt-2.png \
                   sfc_aodtot-0.png  \
                   sfc_aodtot-1.png  \
                   sfc_aodtot-2.png  \
                   sfc_aod-0.png     \
                   sfc_aod-1.png     \
                   sfc_aod-2.png     \
                   h50_ozone-0.png   \
                   h50_ozone-1.png   \
                   h50_ozone-2.png   \
                   pv2_ptemp-0.png   \
                   pv2_ptemp-1.png   \
                   pv2_ptemp-2.png   \
                   pv2_wind-0.png    \
                   pv2_wind-1.png    \
                   pv2_wind-2.png    \
                   pv2_pres-0.png    \
                   pv2_pres-1.png    \
                   pv2_pres-2.png
  
    set -A monpngs montage.png

    set -A kioskpngs 10m_wind_kiosk.png  \
                     sfc_acp_kiosk.png   \
                     sfc_acsnw_kiosk.png

    set -A webnames temp_sfc    \
                    wind_850    \
                    wind_250    \
                    wind_25     \
                    wind_20     \
                    wind_10     \
                    wind_5      \
                    wmag_850    \
                    wmag_250    \
                    wmag_25     \
                    wmag_20     \
                    wmag_10     \
                    wmag_5      \
                    pwtr_sfc    \
                    cwat_sfc    \
                    mslp_sfc    \
                    temp_10     \
                    temp_500    \
                    temp_700    \
                    temp_850    \
                    temp_925    \
                    hgt_500     \
                    rh_500      \
                    rh_850      \
                    vort_500    \
                    vvel_700    \
                    shtfl_sfc   \
                    lhtfl_sfc   \
                    dswrf_sfc   \
                    dlwrf_sfc   \
                    uswrf_sfc   \
                    ulwrf_sfc   \
                    ulwrf_nta   \
                    temp_2m     \
                    temp_2ds    \
                    dewp_2m     \
                    wind_10m    \
                    wind_80m    \
                    totp_sfc    \
                    totp_12h    \
                    totp_24h    \
                    3hap_sfc    \
                    hvyacp_esbl \
                    acpcp_sfc   \
                    weasd_sfc   \
                    acsnw_sfc   \
                    totsn_sfc   \
                    totsn_12h   \
                    totsn_24h   \
                    ceil        \
                    ctop        \
                    rhpw_sfc    \
                    fd_sfc      \
                    bc_sfc      \
                    oc_sfc      \
                    sulf_sfc    \
                    seasalt_sfc \
                    PM10_sfc    \
                    PM25_sfc    \
                    fd_col      \
                    bc_col      \
                    oc_col      \
                    sulf_col    \
                    seasalt_col \
                    PM10_col    \
                    PM25_col    \
                    tozne_col   \
                    aodfd_sfc   \
                    aodbc_sfc   \
                    aodoc_sfc   \
                    aodsulf_sfc \
                    aodseasalt_sfc \
                    aodtot_sfc  \
                    aod_sfc     \
                    ozone_h50   \
                    ptemp_pv2   \
                    wind_pv2    \
                    pres_pv2

    set -A webmon montage

  fi # FIM-8, FIM-9, FIMX, FIMY, FIMZ, FIMALT, FIM7ALT, FIMXALT FV3GFS

fi # nat == 1

ncl_error=0

# Run the NCL scripts for each plot

i=0
while [ ${i} -lt ${#ncgms[@]} ]; do

  plot=${ncgms[${i}]}
  ${ECHO} "Starting fim_${plot}.ncl at `${DATE}`"
  ${NCL} < ${NCL_ROOT}/fim_${plot}.ncl
  error=$?
  if [ ${error} -ne 0 ]; then
    ${ECHO} "ERROR: ${plot} crashed!  Exit status=${error}"
    ncl_error=${error}
  fi
  ${ECHO} "Finished fim_${plot}.ncl at `${DATE}`"

  (( i=i + 1 ))

done

# Run the NCL scripts for the kiosk plots

if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then
  i=0
  while [ ${i} -lt ${#kioskncgms[@]} ]; do

    plot=${kioskncgms[${i}]}
    ${ECHO} "Starting fim_${plot}.ncl at `${DATE}`"
    ${NCL} < ${NCL_ROOT}/fim_${plot}.ncl
    error=$?
    if [ ${error} -ne 0 ]; then
      ${ECHO} "ERROR: ${plot} crashed!  Exit status=${error}"
      ncl_error=${error}
    fi
    ${ECHO} "Finished fim_${plot}.ncl at `${DATE}`"

    (( i=i + 1 ))

  done
fi

# Run ctrans on all the .ncgm files to translate them into Sun Raster files

i=0
while [ ${i} -lt ${#ncgms[@]} ]; do

  plot=${ncgms[${i}]}
  ${ECHO} "Starting ctrans for ${plot}.ncgm at `${DATE}`"
 
  # normal image
  ${CTRANS} -d sun ${plot}.ncgm -resolution 1132x906 > ${plot}.ras
  error=$?
  if [ ${error} -ne 0 ]; then
    ${ECHO} "ERROR: ctrans ${plot}.ncgm crashed!  Exit status=${error}"
    ncl_error=${error}
  fi

  if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then

    # montage image
    ${CTRANS} -d sun ${plot}.ncgm -resolution 3048x1904 > ${plot}_mon.ras
    error=$?
    if [ ${error} -ne 0 ]; then
      ${ECHO} "ERROR: ctrans ${plot}.ncgm crashed!  Exit status=${error}"
      ncl_error=${error}
    fi
    ls -al ${plot}_mon.ras
    if [ -s ${plot}_mon.ras ]; then
      ${CONVERT} -trim -border 86x18 -bordercolor black ${plot}_mon.ras ${plot}_mon.ras
      error=$?
      if [ ${error} -ne 0 ]; then
        ${ECHO} "ERROR: convert ${plot}_mon.ras crashed!  Exit status=${error}"
        ncl_error=${error}
      fi
    else
      ${ECHO} "No file to convert, exit gracefully"
      ncl_error=0
    fi

  fi

  ${ECHO} "Finished ctrans for ${plot}.ncgm at `${DATE}`"

  (( i=i + 1 ))

done

# kiosk images
if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then
  i=0
  while [ ${i} -lt ${#kioskncgms[@]} ]; do

    plot=${kioskncgms[${i}]}
    ${ECHO} "Starting convert for ${plot}.png at `${DATE}`"

    if [ -s ${plot}.png ]; then
      ${CONVERT} -trim -border 25x25 -bordercolor black ${plot}.png ${plot}.png
      error=$?
      if [ ${error} -ne 0 ]; then
        ${ECHO} "ERROR: convert ${plot}.png crashed!  Exit status=${error}"
        ncl_error=${error}
      fi
    else
      ${ECHO} "No file to convert, exit gracefully"
      ncl_error=0
    fi

    ${ECHO} "Finished convert for ${plot}.png at `${DATE}`"

    (( i=i + 1 ))

  done
fi

#
# Convert the .ras files into .png files
i=0
while [ ${i} -lt ${#ncgms[@]} ]; do

  plot=${ncgms[${i}]}
  ${ECHO} "Starting convert for ${plot}.ras at `${DATE}`"

  # normal image
  ls -al ${plot}.ras
  if [ -s ${plot}.ras ]; then
    ${CONVERT} -colors 128 -trim -border 25x25 -bordercolor black ${plot}.ras ${plot}.png
    error=$?
    if [ ${error} -ne 0 ]; then
      ${ECHO} "ERROR: convert ${plot}.ras crashed!  Exit status=${error}"
      ncl_error=${error}
    fi
  else
    ${ECHO} "No file to convert, exit gracefully"
    ncl_error=0
  fi

  if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then
    # montage image
    ls -al ${plot}_mon.ras
    if [ -s ${plot}_mon.ras ]; then
      ${CONVERT} ${plot}_mon.ras ${plot}_mon.png
      error=$?
      if [ ${error} -ne 0 ]; then
        ${ECHO} "ERROR: convert ${plot}_mon.ras crashed!  Exit status=${error}"
        ncl_error=${error}
      fi
    else
      ${ECHO} "No file to convert, exit gracefully"
      ncl_error=0
    fi
  fi

  ${ECHO} "Finished convert for ${plot}.ras at `${DATE}`"

  (( i=i + 1 ))
  
done

if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then

  # put together the montage images
  # -geometry formerly 1240x775+20+1
  ${ECHO} "Prior to montage"
  ls -al
  if [[ -s 250_wind_mon.png || -s sfc_pwtr_mon-0.png || -s 850_temp_mon.png || -s sfc_acp_mon-0.png ]]; then
    ${MONTAGE} 250_wind_mon.png sfc_pwtr_mon-0.png 850_temp_mon.png sfc_acp_mon-0.png -tile 2x2 -geometry 1877x1047+21+4 -background black montage.png
    error=$?
    if [ ${error} -ne 0 ]; then
      ${ECHO} "WARNING:  changing ncl_error to 0 since the sfc_totp_mon.png file is not available at analysis time."
      ncl_error=0
    fi
  else
    ${ECHO} "No files available to montage, exit gracefully"
    ncl_error=0
  fi
fi

if [[ "$GRID_NAME" = "fim" ]]; then

# Create output directories
  fimdir=${FV3GFS_RUN}/ncl/fim
  ${MKDIR} -p ${fimdir}
  taiwandir=${FV3GFS_RUN}/ncl/taiwan
  ${MKDIR} -p ${taiwandir}

# Copy png files to their proper names
  i=0
  j=0
  while [ ${i} -lt ${#pngsfim[@]} ]; do

    pngfile=${pngsfim[${i}]}
    webfile=${fimdir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngsfim[${i}]}
    webfile=${taiwandir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))

    (( j=j + 1 ))

  done

fi

if [[ "$GRID_NAME" = "130" ]]; then

# Create output directories
  conusdir=${FV3GFS_RUN}/ncl/130
  ${MKDIR} -p ${conusdir}
  t1dir=${FV3GFS_RUN}/ncl/t1
  ${MKDIR} -p ${t1dir}
  t2dir=${FV3GFS_RUN}/ncl/t2
  ${MKDIR} -p ${t2dir}
  t3dir=${FV3GFS_RUN}/ncl/t3
  ${MKDIR} -p ${t3dir}
  t4dir=${FV3GFS_RUN}/ncl/t4
  ${MKDIR} -p ${t4dir}
  t5dir=${FV3GFS_RUN}/ncl/t5
  ${MKDIR} -p ${t5dir}
  t6dir=${FV3GFS_RUN}/ncl/t6
  ${MKDIR} -p ${t6dir}
  t7dir=${FV3GFS_RUN}/ncl/t7
  ${MKDIR} -p ${t7dir}

# Copy png files to their proper names
  i=0
  j=0
  while [ ${i} -lt ${#pngs130[@]} ]; do

    pngfile=${pngs130[${i}]}
    webfile=${conusdir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t1dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t2dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t3dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t4dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t5dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t6dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs130[${i}]}
    webfile=${t7dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))

    (( j=j + 1 ))

  done

#  cd ${conusdir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t1dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t2dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t3dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t4dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t5dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t6dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${t7dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png

fi

if [[ "$GRID_NAME" = "174" ]]; then

# Create output directories
  africadir=${FV3GFS_RUN}/ncl/africa
  ${MKDIR} -p ${africadir}
  epacificdir=${FV3GFS_RUN}/ncl/e_pacific
  ${MKDIR} -p ${epacificdir}
  europedir=${FV3GFS_RUN}/ncl/europe
  ${MKDIR} -p ${europedir}
  floatingdir=${FV3GFS_RUN}/ncl/floating
  ${MKDIR} -p ${floatingdir}
  wpacificdir=${FV3GFS_RUN}/ncl/w_pacific
  ${MKDIR} -p ${wpacificdir}
  cambodiadir=${FV3GFS_RUN}/ncl/cambodia
  ${MKDIR} -p ${cambodiadir}

# Copy png files to their proper names
  i=0
  j=0
  while [ ${i} -lt ${#pngs174[@]} ]; do

    pngfile=${pngs174[${i}]}
    webfile=${africadir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs174[${i}]}
    webfile=${epacificdir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs174[${i}]}
    webfile=${europedir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs174[${i}]}
    webfile=${floatingdir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs174[${i}]}
    webfile=${wpacificdir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs174[${i}]}
    webfile=${cambodiadir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))

    (( j=j + 1 ))

  done

#  cd ${africadir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${epacificdir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${europedir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${floatingdir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${wpacificdir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${cambodiadir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png

fi

if [[ "$GRID_NAME" = "242" ]]; then

# Create output directories
  dir=${FV3GFS_RUN}/ncl/242
  ${MKDIR} -p ${dir}
  a1dir=${FV3GFS_RUN}/ncl/a1
  ${MKDIR} -p ${a1dir}
  a2dir=${FV3GFS_RUN}/ncl/a2
  ${MKDIR} -p ${a2dir}

# Copy png files to their proper names
  i=0
  j=0
  while [ ${i} -lt ${#pngs242[@]} ]; do

    pngfile=${pngs242[${i}]}
    webfile=${dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs242[${i}]}
    webfile=${a1dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
    pngfile=${pngs242[${i}]}
    webfile=${a2dir}/${webnames[${j}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))

    (( j=j + 1 ))

  done

#  cd ${dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${a1dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
#  cd ${a2dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png

fi

if [[ "$GRID_NAME" != "fim" && "$GRID_NAME" != "130" && "$GRID_NAME" != "174" && "$GRID_NAME" != "242" ]]; then

# Create output directory
  dir=${FV3GFS_RUN}/ncl/${GRID_NAME}
  ${MKDIR} -p ${dir}

# Copy png files to their proper names
  i=0
  while [ ${i} -lt ${#pngs[@]} ]; do

    pngfile=${pngs[${i}]}
    webfile=${dir}/${webnames[${i}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))

  done

#  cd ${dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png

fi

if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then

  cd ${workdir}

# Create output directory
  kioskdir=${FV3GFS_RUN}/ncl/kiosk
  ${MKDIR} -p ${kioskdir}

# Copy png files to their proper names
  i=0
  while [ ${i} -lt ${#kioskpngs[@]} ]; do

    pngfile=${kioskpngs[${i}]}
    webfile=${kioskdir}/${kioskncgms[${i}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))

  done

#    cd ${kioskdir}
#    zip -g -0 files.zip * -i \*${FCST_TIME}.png

fi

if [[ "$MODL" = *FV3* ]] && [[ "$GRID_NAME" = "fim" ]]; then
 
  cd ${workdir}

  # Copy montage files to their proper names
  i=0
  while [ ${i} -lt ${#monpngs[@]} ]; do
    pngfile=${monpngs[${i}]}
    webfile=${FV3GFS_RUN}/ncl/${GRID_NAME}/${webmon[${i}]}_f${FCST_TIME}.png
    ${MV} ${pngfile} ${webfile}
    (( i=i + 1 ))
  done  

#  dir=${FV3GFS_RUN}/ncl/${GRID_NAME}
#  cd ${dir}
#  zip -g -0 files.zip * -i \*${FCST_TIME}.png
  
fi

# Remove the workdir
cd ${workdir}
cd ../
${RM} -rf ${workdir}

# Hack to prevent errors for analysis file from crashing the whole thing
if [[ ${FCST_TIME} -eq 0  ]]; then
  ncl_error=0
fi

${ECHO} "batchTemplate-ncl completed at `${DATE}`"

